services:
  api:
    env_file: ./backend/.env
    build:
      context: ./backend
    environment:
      - OLLAMA_ENDPOINT=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_data
      - pip_cache:/root/.cache/pip
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=skillsetu
      - POSTGRES_PASSWORD=skillsetu
      - POSTGRES_DB=skillsetu
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
  chroma_data:
  pip_cache:
